package de.sbayat.sbtablereservationmanagementsystem.model;


import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * The Reservation class represents a dining table reservation in a restaurant.
 * It stores details such as the customer's name, phone number, party size,
 * reservation date and time, and assigned table number.
 * <p>
 * This class implements CsvHandling, allowing reservations to be serialized
 * and deserialized in CSV format.
 */
public class Reservation implements CsvHandling {

    private static final String    NO_VALUE_YET  = ">noValueYet";
    private static final int       DEFAULT_VALUE = -1;
    private static final LocalDate DEFAULT_DATE  = LocalDate.of(9999, 12, 31);

    private static final int SPLIT_INDEX_ID              = 0;
    private static final int SPLIT_INDEX_CUSTOMER_NAME   = 1;
    private static final int SPLIT_CUSTOMER_PHONE_NUMBER = 2;
    private static final int SPLIT_INDEX_PARTY_SIZE      = 3;
    private static final int SPLIT_INDEX_DATE            = 4;
    private static final int SPLIT_INDEX_TIME            = 5;
    private static final int SPLIT_INDEX_TABLE_NUMBER    = 6;

    private int id;

    private String customerName;
    private String customerPhoneNumber;
    private int    partySize;

    private LocalDate date;
    private String    time;

    private int tableNumber;

    public Reservation() {
        this.id                  = DEFAULT_VALUE;
        this.customerName        = NO_VALUE_YET;
        this.customerPhoneNumber = NO_VALUE_YET;
        this.partySize           = DEFAULT_VALUE;
        this.date                = DEFAULT_DATE;
        this.time                = NO_VALUE_YET;
        this.tableNumber         = DEFAULT_VALUE;
    }

    // constructor without id in case the id is generated by the db
    public Reservation(String customerName, String customerPhoneNumber, int partySize, LocalDate date, String time, int tableNumber) {
        this.customerName        = customerName;
        this.customerPhoneNumber = customerPhoneNumber;
        this.partySize           = partySize;
        this.date                = date;
        this.time                = time;
        this.tableNumber         = tableNumber;
    }

    // constructor with the id
    public Reservation(int id, String customerName, String customerPhoneNumber, int partySize, LocalDate date, String time, int tableNumber) {
        this.id                  = id;
        this.customerName        = customerName;
        this.customerPhoneNumber = customerPhoneNumber;
        this.partySize           = partySize;
        this.date                = date;
        this.time                = time;
        this.tableNumber         = tableNumber;

    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCustomerPhoneNumber() {
        return customerPhoneNumber;
    }

    public void setCustomerPhoneNumber(String customerPhoneNumber) {
        this.customerPhoneNumber = customerPhoneNumber;
    }

    public Integer getPartySize() {
        return partySize;
    }

    public void setPartySize(int partySize) {
        this.partySize = partySize;
    }

    public LocalDate getDate() {
        return date;
    }

    public String getDateAsString() {
        return date.format(DateTimeFormatter.ISO_LOCAL_DATE); // Format as "yyyy-MM-dd"
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getTableNumber() {
        return tableNumber;
    }

    public void setTableNumber(int tableNumber) {
        this.tableNumber = tableNumber;
    }

    @Override
    public String toString() {
        return "Reservation{" +
                "id=" + id +
                ", customerName='" + customerName + '\'' +
                ", customerPhoneNumber='" + customerPhoneNumber + '\'' +
                ", partySize=" + partySize +
                ", date='" + date + '\'' +
                ", time='" + time + '\'' +
                ", tableNumber=" + tableNumber +
                '}';
    }

    @Override
    public String getAllAttributesAsCsvLine() {
        return getId() + CSV_SEPARATOR +
                getCustomerName() + CSV_SEPARATOR +
                getCustomerPhoneNumber() + CSV_SEPARATOR +
                getPartySize() + CSV_SEPARATOR +
                getDate() + CSV_SEPARATOR +
                getTime() + CSV_SEPARATOR +
                getTableNumber() + "\n";
    }

    @Override
    public void setAllAttributesFromCsvLine(String csvLine) {
        String[] allAttributes = csvLine.split(CSV_SEPARATOR);

        setId(Integer.parseInt(allAttributes[SPLIT_INDEX_ID]));
        setCustomerName(allAttributes[SPLIT_INDEX_CUSTOMER_NAME]);

        setCustomerPhoneNumber(allAttributes[SPLIT_CUSTOMER_PHONE_NUMBER]);
        setPartySize(Integer.parseInt(allAttributes[SPLIT_INDEX_PARTY_SIZE]));
        //TODO: check if this actually works
        setDate(LocalDate.parse(allAttributes[SPLIT_INDEX_DATE]));
        setTime(allAttributes[SPLIT_INDEX_TIME]);
        setTableNumber(Integer.parseInt(allAttributes[SPLIT_INDEX_TABLE_NUMBER]));
    }

    public String showReservationInfo() {
        return String.format("Reservation Number: %d | Name: %s | Party Size: %d | Date: %s | Time: %s | Table Number %d | Phone Number: %s",
                getId(), getCustomerName(), getPartySize(), getDate(), getTime(), getTableNumber(), getCustomerPhoneNumber());
    }
}
