package de.sbayat.sbtablereservationmanagementsystem.model;

public class Reservation implements CsvHandling {

    private static final String NO_VALUE_YET  = ">noValueYet";
    private static final int    DEFAULT_VALUE = -1;

    private static final int SPLIT_INDEX_ID              = 0;
    private static final int SPLIT_INDEX_CUSTOMER_NAME   = 1;
    private static final int SPLIT_CUSTOMER_PHONE_NUMBER = 2;
    private static final int SPLIT_INDEX_PARTY_SIZE      = 3;
    private static final int SPLIT_INDEX_DATE            = 4;
    private static final int SPLIT_INDEX_TIME            = 5;
    private static final int SPLIT_INDEX_TABLE_NUMBER    = 6;

    private int id;

    private String customerName;
    private String customerPhoneNumber;
    private int    partySize;

    private String date;
    private String time;

    private int tableNumber;

    public Reservation() {
        this.id                  = DEFAULT_VALUE;
        this.customerName        = NO_VALUE_YET;
        this.customerPhoneNumber = NO_VALUE_YET;
        this.partySize           = DEFAULT_VALUE;
        this.date                = NO_VALUE_YET;
        this.time                = NO_VALUE_YET;
        this.tableNumber         = DEFAULT_VALUE;
    }

    // constructor without id in case the id is generated by the db
    public Reservation(String customerName, String customerPhoneNumber, int partySize, String date, String time, int tableNumber) {
        this.customerName        = customerName;
        this.customerPhoneNumber = customerPhoneNumber;
        this.partySize           = partySize;
        this.date                = date;
        this.time                = time;
        this.tableNumber         = tableNumber;
    }

    // constructor with the id
    public Reservation(int id, String customerName, String customerPhoneNumber, int partySize, String date, String time, int tableNumber) {
        this.id                  = id;
        this.customerName        = customerName;
        this.customerPhoneNumber = customerPhoneNumber;
        this.partySize           = partySize;
        this.date                = date;
        this.time                = time;
        this.tableNumber         = tableNumber;

    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCustomerPhoneNumber() {
        return customerPhoneNumber;
    }

    public void setCustomerPhoneNumber(String customerPhoneNumber) {
        this.customerPhoneNumber = customerPhoneNumber;
    }

    public Integer getPartySize() {
        return partySize;
    }

    public void setPartySize(int partySize) {
        this.partySize = partySize;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getTableNumber() {
        return tableNumber;
    }

    public void setTableNumber(int tableNumber) {
        this.tableNumber = tableNumber;
    }

    @Override
    public String toString() {
        return "Reservation{" +
                "id=" + id +
                ", customerName='" + customerName + '\'' +
                ", customerPhoneNumber='" + customerPhoneNumber + '\'' +
                ", partySize=" + partySize +
                ", date='" + date + '\'' +
                ", time='" + time + '\'' +
                ", tableNumber=" + tableNumber +
                '}';
    }

    @Override
    public String getAllAttributesAsCsvLine() {
        return getId() + CSV_SEPARATOR +
                getCustomerName() + CSV_SEPARATOR +
                getCustomerPhoneNumber() + CSV_SEPARATOR +
                getPartySize() + CSV_SEPARATOR +
                getDate() + CSV_SEPARATOR +
                getTime() + CSV_SEPARATOR +
                getTableNumber() + "\n";
    }

    @Override
    public void setAllAttributesFromCsvLine(String csvLine) {
        String[] allAttributes = csvLine.split(CSV_SEPARATOR);

        setId(Integer.parseInt(allAttributes[SPLIT_INDEX_ID]));
        setCustomerName(allAttributes[SPLIT_INDEX_CUSTOMER_NAME]);

        setCustomerPhoneNumber(allAttributes[SPLIT_CUSTOMER_PHONE_NUMBER]);
        setPartySize(Integer.parseInt(allAttributes[SPLIT_INDEX_PARTY_SIZE]));

        setDate(allAttributes[SPLIT_INDEX_DATE]);
        setTime(allAttributes[SPLIT_INDEX_TIME]);
        setTableNumber(Integer.parseInt(allAttributes[SPLIT_INDEX_TABLE_NUMBER]));
    }

    public boolean conflictsWith(Reservation other) {
        return this.date.equals(other.date) &&
                this.time.equals(other.time) &&
                this.tableNumber == other.tableNumber;
    }

    public String showReservationInfo() {
        return String.format("ID: %d | Name: %s | Party Size: %d | Date: %s | Time: %s | Table Number %d | Phone Number: %s", getId(), getCustomerName(), getPartySize(), getDate(), getTime(), getTableNumber(), getCustomerPhoneNumber());
    }
}
